# Generated by Django 6.0.4 on 2026-05-11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0011_alter_category_options"),
        ("users", "0010_add_social_links_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id_enrollments",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_column="id_order",
                        null=True,
                    ),
                ),
                (
                    "access_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "access_granted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("access_until", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="id_course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        db_column="id_student_profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-access_granted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student_profile", "course"),
                name="unique_enrollment_per_student_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("access_until__isnull", True))
                    | models.Q(("access_until__gte", models.F("access_granted_at")))
                ),
                name="enrollment_access_until_after_granted_at",
            ),
        ),
    ]
