# Generated by Django 6.0.4 on 2026-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
