# Generated by Django 6.0.4 on 2026-05-30 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0006_lesson_meeting_url"),
        ("enrollments", "0004_add_course_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="curriculum.lesson",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="lessons_completed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="LessonCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_completions",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="curriculum.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_completions",
                "ordering": ["-completed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "lesson"),
                        name="unique_lesson_completion_per_enrollment",
                    )
                ],
            },
        ),
    ]
