# Generated by Django 6.0.4 on 2026-06-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_add_date_range_unavailability'),
        ('enrollments', '0005_enrollment_last_lesson_enrollment_last_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='delivery_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.coursedeliveryformat'),
        ),
    ]
