# Generated by Django 6.0.4 on 2026-07-03 20:49

import apps.common.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_add_delivery_format_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('certificates')),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='paid_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
