# Generated by Django 6.0.4 on 2026-07-03 22:49

import apps.common.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_coursecompletion_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='certificate_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('certificates/thumbnails')),
        ),
    ]
