# Generated by Django 6.0.4 on 2026-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_coursecompletion_certificate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='access_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended (payment overdue)')], default='active', max_length=20),
        ),
    ]
