# Generated by Django 6.0.4 on 2026-07-22 09:08

import apps.common.files
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0047_course_title_created_at_db_index"),
        ("enrollments", "0008_coursecompletion_certificate_thumbnail"),
        ("users", "0016_user_date_joined_db_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=32, unique=True)),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("course_title", models.CharField(max_length=255)),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("valid", "Valid"), ("revoked", "Revoked")],
                        db_index=True,
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "issue_reason",
                    models.CharField(
                        choices=[
                            ("completion", "Completion"),
                            ("manual", "Manual"),
                            ("reissue", "Reissue"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                ("issue_note", models.TextField(blank=True, default="")),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("restore_reason", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.files.UUIDUploadTo("certificates"),
                    ),
                ),
                (
                    "certificate_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.files.UUIDUploadTo(
                            "certificates/thumbnails"
                        ),
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="enrollments.coursecompletion",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="certificates.certificate",
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["student_profile", "status"],
                        name="certificate_student_87e3f0_idx",
                    ),
                    models.Index(
                        fields=["course", "status"],
                        name="certificate_course__9a6b69_idx",
                    ),
                    models.Index(
                        fields=["issued_at"], name="certificate_issued__efb0ed_idx"
                    ),
                ],
            },
        ),
    ]
