# Generated by Django 6.0.4 on 2026-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_backfill_completion_certificates"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="completion_reverted",
            field=models.BooleanField(default=False),
        ),
    ]
