# Generated by Django 6.0.4 on 2026-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_cohort'),
        ('schedule', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='schedule_slots',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='schedule.scheduleslot'),
        ),
    ]
