# Generated by Django 6.0.4 on 2026-06-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_lesson_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='original_video_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
    ]
