# Generated by Django 6.0.4 on 2026-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_lesson_meeting_url'),
        ('curriculum', '0007_remove_lesson_body_html_remove_lesson_content_and_more'),
    ]

    operations = [
    ]
