# Generated by Django 6.0.4 on 2026-06-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0008_merge_20260617_1228"),
        ("users", "0012_merge_20260515_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="accepted_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_indices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="test",
            name="allow_retakes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                ],
                default="single_choice",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField()),
                ("passed", models.BooleanField()),
                ("answers", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="curriculum.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_attempts",
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile", "test", "attempt_number"),
                        name="unique_attempt_number_per_student_test",
                    )
                ],
            },
        ),
    ]
