# Generated by Django 6.0.4 on 2026-06-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0010_backfill_correct_indices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_index",
        ),
    ]
