# Generated by Django 6.0.4 on 2026-06-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0010_lesson_is_manually_locked"),
        ("curriculum", "0011_remove_question_correct_index"),
    ]

    operations = []
