# Generated by Django 6.0.4 on 2026-07-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_course_image_alter_coursependingedit_image'),
        ('curriculum', '0013_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='lessondocument',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.lessondocument'),
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='source_lesson_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.lessonitem'),
        ),
        migrations.AddField(
            model_name='module',
            name='source_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.module'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.question'),
        ),
        migrations.AddField(
            model_name='test',
            name='source_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='curriculum.test'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('source_lesson__isnull', False)), fields=('source_lesson',), name='unique_source_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('source_document__isnull', False)), fields=('source_document',), name='unique_source_document'),
        ),
        migrations.AddConstraint(
            model_name='lessonitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_lesson_item__isnull', False)), fields=('source_lesson_item',), name='unique_source_lesson_item'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(condition=models.Q(('source_module__isnull', False)), fields=('source_module',), name='unique_source_module'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('source_question__isnull', False)), fields=('source_question',), name='unique_source_question'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('source_test__isnull', False)), fields=('source_test',), name='unique_source_test'),
        ),
    ]
