# Generated by Django 6.0.4 on 2026-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_lesson_source_lesson_lessondocument_source_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
