# Generated by Django 6.0.4 on 2026-07-03 15:05

from django.db import migrations, models
from django.db.models import Q


def copy_content_into_body_html(apps, schema_editor):
    """Some LessonItem rows only ever had the plain `content` field filled in
    (the teacher-facing editor never wrote to `body_html`). Before dropping
    `content`, fold any such text into `body_html` so it isn't lost — rows that
    already have real `body_html` are left untouched."""
    LessonItem = apps.get_model("curriculum", "LessonItem")
    LessonItem.objects.filter(
        Q(body_html__isnull=True) | Q(body_html=""),
    ).exclude(content="").update(body_html=models.F("content"))


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_lesson_is_mandatory'),
    ]

    operations = [
        migrations.RunPython(copy_content_into_body_html, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lessonitem',
            name='content',
        ),
    ]
