# Generated by Django 6.0.4 on 2026-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_remove_lesson_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonitem',
            name='video_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
