# Generated by Django 6.0.4 on 2026-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_backfill_note_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='course_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
