# Generated by Django 6.0.3 on 2026-04-22 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_add_is_email_verified_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.CharField(max_length=500)),
                ("full_description", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                ("level", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")], max_length=20)),
                ("language", models.CharField(choices=[("english", "English"), ("ukrainian", "Ukrainian"), ("spanish", "Spanish")], default="english", max_length=20)),
                ("mode", models.CharField(choices=[("self_learning", "РЎР°РјРѕРЅР°РІС‡Р°РЅРЅСЏ"), ("with_teacher", "РќР°РІС‡Р°РЅРЅСЏ Р· РІРёРєР»Р°РґР°С‡РµРј")], max_length=20)),
                ("delivery_type", models.CharField(choices=[("self_paced", "Self-paced"), ("scheduled", "Scheduled"), ("individual", "Р†РЅРґРёРІС–РґСѓР°Р»СЊРЅРѕ"), ("group", "Р“СЂСѓРїР°")], max_length=20)),
                ("course_type", models.CharField(choices=[("profession", "РџСЂРѕС„РµСЃС–СЏ"), ("qualification", "РџС–РґРІРёС‰РµРЅРЅСЏ РєРІР°Р»С–С„С–РєР°С†С–С—"), ("knowledge", "Р РѕР·С€РёСЂРµРЅРЅСЏ Р·РЅР°РЅСЊ")], max_length=30)),
                ("pricing_type", models.CharField(choices=[("free", "Р‘РµР·РєРѕС€С‚РѕРІРЅРёР№"), ("full_payment", "РџРѕРІРЅР° РѕРїР»Р°С‚Р°"), ("installment", "РћРїР»Р°С‚Р° С‡Р°СЃС‚РёРЅР°РјРё")], default="free", max_length=20)),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("installment_count", models.PositiveIntegerField(blank=True, null=True)),
                ("installment_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("duration_hours", models.PositiveIntegerField()),
                ("lessons_count", models.PositiveIntegerField(default=0)),
                ("with_certificate", models.BooleanField(default=False)),
                ("is_on_sale", models.BooleanField(default=False)),
                ("rating_avg", models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("students_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="courses", to="courses.category")),
                ("moderator_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moderated_courses", to="users.moderatorprofile")),
                ("teacher_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="courses", to="users.teacherprofile")),
                ("tags", models.ManyToManyField(blank=True, related_name="courses", to="courses.tag")),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
    ]
