# Generated by Django 6.0.3 on 2026-04-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("profession", "Професія"),
                    ("qualification", "Підвищення кваліфікації"),
                    ("knowledge", "Розширення знань"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("self_paced", "Self-paced"),
                    ("scheduled", "Scheduled"),
                    ("individual", "Індивідуально"),
                    ("group", "Група"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="mode",
            field=models.CharField(
                choices=[
                    ("self_learning", "Самонавчання"),
                    ("with_teacher", "Навчання з викладачем"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("free", "Безкоштовний"),
                    ("full_payment", "Повна оплата"),
                    ("installment", "Оплата частинами"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
