# Generated by Django 6.0.3 on 2026-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_alter_course_course_type_alter_course_delivery_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="installment_amount",
        ),
        migrations.RemoveField(
            model_name="course",
            name="installment_count",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("profession", "Profession"),
                    ("qualification", "Qualification"),
                    ("knowledge", "Knowledge"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("self_paced", "Self-paced"),
                    ("scheduled", "Scheduled"),
                    ("individual", "Individual"),
                    ("group", "Group"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="mode",
            field=models.CharField(
                choices=[
                    ("self_learning", "Self Learning"),
                    ("with_teacher", "With Teacher"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("full_payment", "Full Payment"),
                    ("installment", "Installment"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
