# Generated by Django 6.0.4 on 2026-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_installment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="installment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="installment_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
