# Generated by Django 6.0.4 on 2026-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_installment_amount_course_installment_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("ukrainian", "Ukrainian"),
                    ("spanish", "Spanish"),
                ],
                default="ukrainian",
                max_length=20,
            ),
        ),
    ]
