# Generated by Django 6.0.4 on 2026-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
