# Generated by Django 6.0.4 on 2026-05-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_image"),
        ("courses", "0008_recompute_lessons_count"),
    ]

    operations = []
