# Generated by Django 6.0.4 on 2026-05-07 23:42

import apps.common.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_merge_0007_course_image_0008_recompute_lessons_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.files.UUIDUploadTo("courses"),
            ),
        ),
    ]
