# Generated by Django 6.0.4 on 2026-05-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_course_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
