# Generated by Django 6.0.4 on 2026-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('needs_revision', 'Needs Revision'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
