# Generated by Django 6.0.4 on 2026-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_status_add_needs_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('needs_revision', 'Needs Revision (returned by moderator)'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
