# Generated by Django 6.0.4 on 2026-05-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_alter_course_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="installment_amount",
        ),
        migrations.RemoveField(
            model_name="course",
            name="installment_count",
        ),
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
        migrations.RemoveField(
            model_name="course",
            name="pricing_type",
        ),
        migrations.AddField(
            model_name="course",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_months", models.PositiveSmallIntegerField()),
                ("hours_per_week_min", models.PositiveSmallIntegerField()),
                ("hours_per_week_max", models.PositiveSmallIntegerField()),
                ("group_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("group", "Group"),
                            ("individual", "Individual"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "cohorts",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("group", "Group"), ("individual", "Individual")],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("UAH", "UAH")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "installment_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_plans",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_plans",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "kind"), name="unique_pricing_plan_per_kind"
                    )
                ],
            },
        ),
    ]
