# Generated by Django 6.0.4 on 2026-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_remove_course_installment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="body_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[("video", "Video"), ("text", "Text")],
                default="video",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
