# Generated by Django 6.0.4 on 2026-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_test_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=70),
        ),
    ]
