# Generated by Django 6.0.4 on 2026-06-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_delivery_formats'),
        ('enrollments', '0005_enrollment_last_lesson_enrollment_last_opened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='hours_per_week_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='hours_per_week_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedeliveryformat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.cohort')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'cohort_members',
                'unique_together': {('cohort', 'enrollment')},
            },
        ),
    ]
