# Generated by Django 6.0.4 on 2026-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_cohort_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='hours_per_week_max',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='hours_per_week_min',
        ),
        migrations.AddField(
            model_name='cohort',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
