# Generated by Django 6.0.4 on 2026-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_cohort_hours_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_enrollment_open',
            field=models.BooleanField(default=True),
        ),
    ]
