# Generated by Django 6.0.4 on 2026-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_schedule_slots_cohort_schedules_teacher_unavailabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherunavailability',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherunavailability',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Every week'), ('one_time', 'One-time block'), ('date_range', 'Date range')], default='weekly', max_length=10),
        ),
    ]
