# Generated by Django 6.0.4 on 2026-06-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_add_date_range_unavailability'),
        ('enrollments', '0006_add_delivery_format_to_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_slots', to='enrollments.enrollment'),
        ),
    ]
