# Generated by Django 6.0.4 on 2026-06-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_meeting_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], max_length=20)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='courses.cohortschedule')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='courses.scheduleslot')),
            ],
            options={
                'db_table': 'slot_overrides',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('schedule__isnull', True), ('slot__isnull', False)), models.Q(('schedule__isnull', False), ('slot__isnull', True)), _connector='OR'), name='slot_override_exactly_one_source')],
            },
        ),
    ]
