# Generated by Django 6.0.4 on 2026-06-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_slot_override'),
        ('curriculum', '0010_lesson_is_manually_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortschedule',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.lesson'),
        ),
    ]
