# Generated by Django 6.0.4 on 2026-06-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_rename_slotoverride_scheduleoverride'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='sessions_schedul_8b7510_idx',
            old_name='sessions_schedule_date_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='sessions_slot_id_9c66f7_idx',
            old_name='sessions_slot_date_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='sessions_course__cc4c6e_idx',
            old_name='sessions_course_date_idx',
        ),
    ]
