# Generated by Django 6.0.4 on 2026-07-01 21:16

import apps.common.files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_move_to_schedule_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('courses'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='coursependingedit',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('courses/pending'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
    ]
