# Generated by Django 6.0.4 on 2026-07-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_course_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
