# Generated by Django 6.0.4 on 2026-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_course_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
