# Generated by Django 6.0.4 on 2026-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0045_backfill_course_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="featured_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
