# Generated by Django 6.0.4 on 2026-07-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_course_discount_percent"),
        ("courses", "0053_merge_0048_cohort_group_chat_0052_category_locales"),
    ]

    operations = []
