# Generated by Django 6.0.4 on 2026-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
