# Generated by Django 6.0.4 on 2026-07-22 17:09

import apps.common.files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('blog'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'jfif', 'webp', 'svg'])]),
        ),
    ]
