# Generated by Django 6.0.4 on 2026-07-24 11:56

import apps.common.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_headline'),
        ('users', '0017_teacherapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModerationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('blog-snapshots'))),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_snapshots', to='blog.article')),
                ('moderator_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_moderation_snapshots', to='users.moderatorprofile')),
            ],
            options={
                'db_table': 'blog_article_moderation_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
