# Generated by Django 6.0.4 on 2026-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderitem_paymentitem_cohort'),
        ('schedule', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='schedule_slots',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='schedule.scheduleslot'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='schedule_slots',
            field=models.ManyToManyField(blank=True, related_name='payment_items', to='schedule.scheduleslot'),
        ),
    ]
