# Generated by Django 6.0.4 on 2026-08-20 18:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0006_paymentattempt_processed_at_paymentattempt_provider_and_more",
        ),
        ("users", "0021_merge_20260725_1221"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("liqpay", "LiqPay"), ("manual", "Manual")],
                        default="liqpay",
                        max_length=20,
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_teacher_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="users.teacherprofile",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("refund", "Refund adjustment"),
                            ("payout", "Payout"),
                            ("adjustment", "Manual adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_ledger_entries",
                        to="payments.payment",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_ledger_entries",
                        to="payments.refund",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="users.teacherprofile",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="payments.teacherpayout",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_ledger_entries",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TeacherPayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_payout_items",
                        to="payments.payment",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.teacherpayout",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_payout_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="teacherpayout",
            index=models.Index(
                fields=["teacher", "currency", "status"],
                name="teacher_payout_balance_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherpayout",
            index=models.Index(
                fields=["provider", "provider_status"],
                name="teacher_payout_provider_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherpayout",
            index=models.Index(
                fields=["created_at"], name="teacher_payout_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="teacher_payout_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpayout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_order_id", ""), _negated=True),
                fields=("provider", "provider_order_id"),
                name="unique_teacher_payout_provider_order",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherledgerentry",
            index=models.Index(
                fields=["teacher", "currency", "status"],
                name="teacher_ledger_balance_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherledgerentry",
            index=models.Index(
                fields=["entry_type", "status"], name="teacher_ledger_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherledgerentry",
            index=models.Index(
                fields=["created_at"], name="teacher_ledger_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", Decimal("0.00")), _negated=True),
                name="teacher_ledger_amount_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpayoutitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="teacher_payout_item_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherpayoutitem",
            constraint=models.UniqueConstraint(
                fields=("payout", "payment"), name="unique_payment_per_teacher_payout"
            ),
        ),
    ]
