# Generated by Django 6.0.4 on 2026-08-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0007_teacherpayout_teacherledgerentry_teacherpayoutitem_and_more",
        ),
        ("users", "0021_merge_20260725_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherpayout",
            name="destination_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TeacherPayoutDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="liqpay", max_length=20)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank account"),
                            ("card_token", "Card token"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "receiver_account",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "receiver_mfo",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "receiver_okpo",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "receiver_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "receiver_card_token",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_destinations",
                        to="users.teacherprofile",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_payout_destinations",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="teacherpayout",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="payments.teacherpayoutdestination",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherpayoutdestination",
            index=models.Index(
                fields=["teacher", "provider", "is_active"],
                name="teacher_payout_dest_idx",
            ),
        ),
    ]
