# Generated by Django 6.0.3 on 2026-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_installment_amount_and_more"),
        ("users", "0004_add_is_email_verified_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="courses.course"
            ),
        ),
    ]
