# Generated by Django 6.0.4 on 2026-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studentprofile_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian")],
                default="uk",
                max_length=10,
            ),
        ),
    ]
