# Generated by Django 6.0.4 on 2026-05-06 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
    ]
