# Generated by Django 6.0.4 on 2026-05-07 23:42

import apps.common.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_related_name_to_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.files.UUIDUploadTo("avatars"),
            ),
        ),
    ]
