# Generated by Django 6.0.4 on 2026-05-11

from django.db import migrations, models
from django.utils import timezone


def copy_existing_student_courses(apps, schema_editor):
    existing_tables = schema_editor.connection.introspection.table_names()
    if "users_studentprofile_courses" not in existing_tables:
        return

    Enrollment = apps.get_model("enrollments", "Enrollment")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT studentprofile_id, course_id
            FROM users_studentprofile_courses
            """
        )
        rows = cursor.fetchall()

    granted_at = timezone.now()
    enrollments = [
        Enrollment(
            student_profile_id=student_profile_id,
            course_id=course_id,
            access_status="active",
            access_granted_at=granted_at,
        )
        for student_profile_id, course_id in rows
    ]
    Enrollment.objects.bulk_create(enrollments, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
        ("users", "0010_add_social_links_to_user"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    copy_existing_student_courses,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="studentprofile",
                    name="courses",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_students",
                        through="enrollments.Enrollment",
                        through_fields=("student_profile", "course"),
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
