# Generated by Django 6.0.4 on 2026-05-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_studentprofile_courses_through_enrollment"),
        ("users", "0011_studentprofile_wishlisted_courses"),
    ]

    operations = []
