# Generated by Django 6.0.4 on 2026-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20260515_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='partnerships_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
