# Generated by Django 6.0.4 on 2026-07-03 20:49

import apps.common.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacherprofile_partnerships_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.files.UUIDUploadTo('teacher_signatures')),
        ),
    ]
