# Generated by Django 6.0.4 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_adminnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam or advertising"),
                            ("harassment", "Harassment or bullying"),
                            ("hate", "Hate speech"),
                            ("violence", "Violence or threats"),
                            ("sexual", "Sexual content"),
                            ("fraud", "Fraud or scam"),
                            ("impersonation", "Impersonation"),
                            ("inappropriate_profile", "Inappropriate profile"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_reports",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.UniqueConstraint(
                fields=("reported_user", "reporter"),
                name="unique_user_reporter_target",
            ),
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(
                fields=["reported_user", "-created_at"],
                name="user_report_target_created_idx",
            ),
        ),
    ]
