# Generated by Django 6.0.4 on 2026-07-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_course_title_created_at_db_index'),
        ('users', '0016_user_date_joined_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True)),
                ('instagram', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('behance', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('moderator_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_application', to=settings.AUTH_USER_MODEL)),
                ('directions', models.ManyToManyField(blank=True, related_name='teacher_applications', to='courses.category')),
                ('moderator_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_application_decisions', to='users.moderatorprofile')),
            ],
            options={
                'db_table': 'teacher_applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
