# Generated by Django 6.0.4 on 2026-07-16 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_userreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReportAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed"),
                            ("warning", "Warning"),
                            ("blocked", "Blocked"),
                            ("escalated", "Escalated"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("previous_status", models.CharField(max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_report_actions",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="userreport",
            name="unique_user_reporter_target",
        ),
        migrations.AddField(
            model_name="userreport",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userreport",
            name="assigned_moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user_reports",
                to="users.moderatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userreport",
            name="escalated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_reports_escalated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="escalation_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userreport",
            name="profile_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="userreport",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warning", "Warning"),
                    ("blocked", "Blocked"),
                    ("dismissed", "Dismissed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="resolution_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userreport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_reports_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_review", "In review"),
                    ("escalated", "Escalated"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(
                fields=["status", "assigned_moderator", "created_at"],
                name="user_report_queue_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "in_review", "escalated"])
                ),
                fields=("reported_user", "reporter"),
                name="unique_active_user_reporter_target",
            ),
        ),
        migrations.AddField(
            model_name="userreportaction",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_report_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreportaction",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="users.userreport",
            ),
        ),
        migrations.AddIndex(
            model_name="userreportaction",
            index=models.Index(
                fields=["report", "-created_at"], name="user_report_action_idx"
            ),
        ),
    ]
