# Generated by Django 6.0.4 on 2026-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_teacherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], default='uk', max_length=10),
        ),
    ]
