# Generated by Django 6.0.4 on 2026-07-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_date_joined_db_index"),
        ("users", "0017_userreportaction_and_more"),
    ]

    operations = []
