# Generated by Django 6.0.4 on 2026-07-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_teacherapplication"),
        ("users", "0019_user_report_unblocked_action"),
    ]

    operations = []
