# Generated by Django 6.0.4 on 2026-07-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_language'),
        ('users', '0020_merge_20260724_1622'),
    ]

    operations = [
    ]
