# Generated by Django 6.0.4 on 2026-06-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0008_merge_20260617_1228"),
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework_assignments",
                to="curriculum.module",
            ),
        ),
    ]
