# Generated by Django 6.0.4 on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0006_add_delivery_format_to_enrollment"),
        ("homework", "0002_homeworkassignment_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homeworkassignment",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HomeworkAssignmentRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="homework.homeworkassignment")),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="homework_recipients", to="enrollments.enrollment")),
            ],
            options={"db_table": "homework_assignment_recipients"},
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("status", models.CharField(choices=[("submitted", "Submitted"), ("reviewed", "Reviewed")], default="submitted", max_length=20)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="homework.homeworkassignment")),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="homework_submissions", to="enrollments.enrollment")),
            ],
            options={"db_table": "homework_submissions"},
        ),
        migrations.AddConstraint(
            model_name="homeworkassignmentrecipient",
            constraint=models.UniqueConstraint(fields=("assignment", "enrollment"), name="unique_homework_assignment_recipient"),
        ),
        migrations.AddConstraint(
            model_name="homeworksubmission",
            constraint=models.UniqueConstraint(fields=("assignment", "enrollment"), name="unique_homework_submission_per_enrollment"),
        ),
    ]
