# Generated by Django 6.0.4 on 2026-06-24

import apps.common.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0003_assignment_recipients_and_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworksubmission",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="HomeworkAssignmentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.common.files.UUIDUploadTo("homework/assignments"))),
                ("original_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="homework.homeworkassignment")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_homework_assignment_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "homework_assignment_attachments", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="HomeworkSubmissionAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.common.files.UUIDUploadTo("homework/submissions"))),
                ("original_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="homework.homeworksubmission")),
            ],
            options={"db_table": "homework_submission_attachments", "ordering": ["created_at"]},
        ),
    ]
