# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0010_lesson_is_manually_locked"),
        ("homework", "0004_homework_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="source_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reused_assignments",
                to="homework.homeworkassignment",
            ),
        ),
        migrations.AddField(
            model_name="homeworkassignment",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework_assignments",
                to="curriculum.test",
            ),
        ),
    ]
