# Generated by Codex on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0012_merge_20260626_1244"),
        ("homework", "0005_homework_assignment_test_reuse"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworksubmission",
            name="best_test_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework_submissions",
                to="curriculum.testattempt",
            ),
        ),
    ]
