from django.urls import path

from apps.reviews.views import (
    CourseReviewsView,
    MyCourseReviewView,
    ReviewApproveView,
    ReviewAssignModeratorView,
    ReviewRejectView,
    ReviewReportView,
    ReviewsMyModerationView,
    ReviewsUnassignedModerationView,
    TopReviewsView,
)

urlpatterns = [
    path(
        "courses/<slug:slug>/reviews/mine/",
        MyCourseReviewView.as_view(),
        name="course-reviews-mine",
    ),
    path(
        "courses/<slug:slug>/reviews/",
        CourseReviewsView.as_view(),
        name="course-reviews",
    ),
    path(
        "reviews/top-reviews/",
        TopReviewsView.as_view(),
        name="top-reviews",
    ),
    path(
        "reviews/moderation/unassigned/",
        ReviewsUnassignedModerationView.as_view(),
        name="reviews-moderation-unassigned",
    ),
    path(
        "reviews/moderation/mine/",
        ReviewsMyModerationView.as_view(),
        name="reviews-moderation-mine",
    ),
    path(
        "reviews/<int:pk>/report/",
        ReviewReportView.as_view(),
        name="review-report",
    ),
    path(
        "reviews/<int:pk>/assign-moderator/",
        ReviewAssignModeratorView.as_view(),
        name="review-assign-moderator",
    ),
    path(
        "reviews/<int:pk>/approve/",
        ReviewApproveView.as_view(),
        name="review-approve",
    ),
    path(
        "reviews/<int:pk>/reject/",
        ReviewRejectView.as_view(),
        name="review-reject",
    ),
]
