# Generated by Django 6.0.4 on 2026-07-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewreport'),
        ('users', '0014_teacherprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='moderator_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to='users.moderatorprofile'),
        ),
    ]
