# Generated by Django 6.0.4 on 2026-07-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
        ("notifications", "0003_add_moderation_action_type"),
    ]

    operations = []
