# Generated by Django 6.0.4 on 2026-07-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
        ("notifications", "0003_add_moderation_action_type"),
    ]

    # Both branches changed this field independently. Re-declare the combined
    # state so a fresh database does not lose choices from whichever branch
    # Django happens to apply first.
    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_message", "New message"),
                    ("homework_submitted", "Homework submitted"),
                    ("homework_graded", "Homework graded"),
                    ("schedule_event", "Schedule event"),
                    ("new_lesson", "New lesson"),
                    ("moderation_action", "Moderation action"),
                    ("course_completed", "Course completed"),
                ],
                max_length=32,
            ),
        ),
    ]
