# Generated by Django 6.0.4 on 2026-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_merge_20260713_1705"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_message", "New message"),
                    ("homework_submitted", "Homework submitted"),
                    ("homework_graded", "Homework graded"),
                    ("schedule_event", "Schedule event"),
                    ("new_lesson", "New lesson"),
                    ("moderation_action", "Moderation action"),
                    ("course_completed", "Course completed"),
                ],
                max_length=32,
            ),
        ),
    ]
