# Generated by Django 6.0.4 on 2026-08-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_merge_20260712_1631"),
        ("notifications", "0006_alter_notification_type"),
    ]

    operations = []
