# Generated by Django 6.0.4 on 2026-07-03 17:11

import apps.common.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("group", "Group")],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.files.UUIDUploadTo("chat/rooms"),
                    ),
                ),
                (
                    "direct_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_rooms",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
            ),
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=12,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_participants",
                "ordering": ["joined_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.common.files.UUIDUploadTo("chat/attachments")
                    ),
                ),
                ("file_type", models.CharField(max_length=128)),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_attachments",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "created_at", "id"], name="chat_msg_chat_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["chat", "id"], name="chat_msg_chat_id_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="chat_msg_sender_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["type", "-updated_at"], name="chat_room_type_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["direct_key"], name="chat_room_direct_key_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "left_at"], name="chat_part_user_left_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["chat", "left_at"], name="chat_part_chat_left_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["chat", "role"], name="chat_part_chat_role_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatparticipant",
            constraint=models.UniqueConstraint(
                fields=("chat", "user"), name="unique_chat_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["message"], name="chat_attachment_message_idx"),
        ),
    ]
